name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # use Node 20 or your version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install ui dependencies
        run: npm install --workspace ui

      - name: Install api dependencies
        run: npm install --workspace api

      - name: Lint UI & API
        run: npm run lint

      # - name: Run tests
      #   run: npm test

      - name: Build UI
        run: npm run build --workspace ui

      - name: Build API
        run: npm run build --workspace api
