name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Test and Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      # Install dependencies for all workspaces
      - name: Install dependencies
        run: npm install

      # Run lint in each workspace
      - name: Lint UI
        run: npm run lint --workspace ui

      - name: Lint API
        run: npm run lint --workspace api

      - name: Generate Prisma client
        run: npm run prisma:generate --workspace api

      # Run tests (if you have them enabled)
      # - name: Run tests UI
      #   run: npm test --workspace ui
      #
      # - name: Run tests API
      #   run: npm test --workspace api

      # Build each workspace
      - name: Build UI
        run: npm run build --workspace ui

      - name: Build API
        run: npm run build --workspace api
